### ISSUE TITLE
Resume restarts last played song

### ISSUE THREAD

**Issue by airix1** [mhilbush/squeezebox-test#1]
Finally found some time to test this.
I noticed when the playlist resumes, it resumes at the beginning of the last played song, as opposed to resuming at the last played point.
This was with songs in my library, haven't played with any streaming service.

Thanks again for working on this!

**Comment by mhilbush** [comment]
Thanks for testing this, @airix1 !

Hmm.  I thought I had it restarting at the last played point for music played from the library.  I'll need to check if I pushed the latest rev of the binding to the test repo.

As for the streaming services, from what I've been able to find so far, I'm not sure it will be possible to restart from the last played point.  In Pandora, once you exceed your max number of skips, then it picks up at the last played point just fine.  ;-)

Let me know if you run into any other issues.

**Comment by airix1** [comment]
Is there a way to define the name of the squeezebox sink?  All 6 of mine list as "Squeezebox" in the sink selection drop down, which makes selecting a particular one difficult.  Other sink devices appear by their name.

**Comment by mhilbush** [comment]
> Is there a way to define the name of the squeezebox sink? 

It should be the name of the Squeezebox player thing.  Here's what my drop down looks like in Paper UI.

![capture](https://cloud.githubusercontent.com/assets/19286354/21903480/1ce4cebe-d8ce-11e6-88b3-9a0810639008.PNG)

> which makes selecting a particular one difficult

Yes, I would imagine so.  ;-)

**Comment by mhilbush** [comment]
When did you pull the jar file that you used to test?  The one I put out there yesterday should be the version that resumes playing at the last point (for music in the library).

**Comment by airix1** [comment]
Yes, using your latest jar now.  Everything is working great!  (Other than squeezelite with voice, hopefully Ralphy can fix that.)

**Comment by mhilbush** [comment]
Ok.  I'm gonna close this.  Feel free to open another issue if you run into anything else.

Did you get the player naming sorted out?
